#!/bin/bash
#
## Usage: kata-local-ci <options>
##   Run or setup local CI environment for kata containers using libvirt.
##
## Options include:
##   -h: Print help
##   -d <distro>: Select VM distro (fedora,ubuntu,centos, default:fedora)
##   -w <dir>: Work directory to test (default $GOPATH/src/github.com/kata-containers)
##   -j <job>: CI job to run (default: all)
##   -f: force install of the VM (and overwrite disk)
##   -F: "Faster" by reusing the image without reverting to earlier snapshot
##
## Creation options include:
##   -k <ssh_key_file> (default ~/.ssh/id_rsa.pub)
##   -o <disk-image>: Path and image name for the VM
##   -s <size>: Disk image size for the VM (default 50G)
##   -m <memory>: Memory for the VM in megabytes (default 8192M)
##   -c <cpus>: Number of CPUs for the VM (default 4)
##   -n network config (optional)
##

distro=fedora
size=50G
memory=8192
cpus=4
key=~/.ssh/id_rsa.pub
vmdir=go/src/github.com/kata-containers
directory=${GOPATH:-~go}/src/github.com/kata-containers
disk=""
network=""
job=""
kci=~/.kata-containers-ci
install=false
revert=true

function help {
    sed -E '/^##/s/^##\s?//g;t;d' $0
}

function progress() {
    printf "******************************************** [$(date +%H:%M:%S)]\n"
    printf "*\n"
    printf "* $1\n"
    printf "*\n"
    printf "********************************************\n"
}


while getopts fFhk:d:o:s:n:w:j: flag
do
    case "${flag}" in
        h) help; exit 0 ;;
        d) distro=$OPTARG;;
        w) directory=$OPTARG;;
        j) job=$OPTARG;;
        v) name=$OPTARG;;
        k) key=$OPTARG;;
	o) disk=$OPTARG;;
	s) size=$OPTARG;;
	c) cpus=$OPTARG;;
	m) memory=$OPTARG;;
	n) network=$OPTARG;;
	f) install=true ;;
        F) revert=false;;
        *) help; exit 1;;
    esac
done

if [ ! -d "$kci" ]; then
    mkdir "$kci"
fi

if [ ! -f "$kci/"$distro-config ]; then
    install=true
fi

if [ -z "$disk" ]; then
    disk=/var/lib/libvirt/images/kata-$distro-ci.qcow2
fi

if [ ! -f "$disk" ] ; then
    install=true
fi

if [ ! -d "$directory"/kata-containers ]; then
    echo "ERROR: The work directory $directory does not contain a 'kata-containers' subdirectory"
    exit 4
fi
if [ ! -d "$directory"/tests ]; then
    echo "ERROR: The work directory $directory does not contain a 'tests' subdirectory"
    exit 4
fi


function vm_install() {
    distro_commands=""
    firstboot_cmds=(
	--firstboot-command 'useradd -m  kata -s /bin/bash'
	--firstboot-command 'echo "kata ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers.d/kata'
	--firstboot-command "echo 'export PATH=\$PATH:/usr/local/go/bin' >> /home/kata/.bashrc"
	--firstboot-command 'mkdir -p /home/kata/.ssh'
	--firstboot-command "echo $(cat $key) > /home/kata/.ssh/authorized_keys"
	--firstboot-command 'chown kata:kata -R /home/kata'
	--firstboot-command 'chown kata:kata -R /home/kata'
        --firstboot-command "swapoff -a"
    )
    final_firstboot_cmd=()
    ubuntu_distro_commands=(
        --firstboot-command 'usermod -a -G sudo kata'
	--update
	--firstboot-command 'dhclient'
	--firstboot-command 'systemctl enable serial-getty@ttyS0'
	--firstboot-command 'systemctl start serial-getty@ttyS0'
    )
    rh_distro_commands=(
        --selinux-relabel
        --edit '/etc/selinux/config:s/SELINUX=enforcing/SELINUX=permissive/'
        --firstboot-command 'systemctl stop firewalld'
        --firstboot-command 'systemctl disable firewalld'
    )
    disable_cgroupv2=(
        --firstboot-command 'grubby --update-kernel=ALL --args="systemd.unified_cgroup_hierarchy=0"'
        --firstboot-command 'reboot'
    )

    case "$distro" in
	ubuntu)
	    distro_name=ubuntu-18.04
	    distro_commands=("${ubuntu_distro_commands[@]}")
	    osvariant=ubuntu18.04
	    ;;
	centos)
	    distro_name=centos-8.2
	    osvariant=centos8
	    distro_commands=("${rh_distro_commands[@]}")
	    ;;
	fedora)
	    distro_name=fedora-32
	    osvariant=fedora32
	    distro_commands=("${rh_distro_commands[@]}")
	    final_firstboot_cmd=("${disable_cgroupv2[@]}")
	    ;;
	*)
	    echo "Distro $1 not recognized. Please choose ubuntu, centos or fedora"
            exit 3
    esac

    if [  ! -z "$network" ]; then
	network="--network $network"
    fi

    VM_NAME=kata-$distro-ci
    progress "Removing earlier VM $VM_NAME"
    echo "The script may now ask you for a password to setup the VM named $VM_NAME"
    echo "You can avoid these prompts by executing:"
    echo "sudo bash -c \"echo > /etc/sudoers.d/kata-local-ci '"$(whoami) "ALL=(ALL) NOPASSWD: /usr/bin/virsh,/usr/bin/virt-install,/usr/bin/virt-builder'\""

    sudo virsh destroy $VM_NAME || true
    sudo virsh undefine $VM_NAME --remove-all-storage  --snapshots-metadata || true

    set -e
    progress "Launching virt-builder"
    sudo virt-builder $distro_name \
         -o $disk --format qcow2 --size=$size \
	 --root-password password:kata \
	 "${distro_commands[@]}" \
	 --mkdir /home/kata \
	 --delete /.autorelabel \
	 --ssh-inject "root:file:$key" \
	 --install "git,rsync,curl,make,tar" \
         "${firstboot_cmds[@]}" \
         "${final_firstboot_cmd[@]}" \
	 --password  'kata:password:kata' \
	 --hostname kata-$distro-ci
    progress "Launching virt-install"
    sudo virt-install --import --name $VM_NAME  --memory $memory --vcpus $cpus \
         --disk path=$disk,format=qcow2 \
         --os-variant=$osvariant --noautoconsole $network

    echo -n "Waiting for guest to get an IP address"
    while ! sudo virsh domifaddr $VM_NAME | grep -q vnet ; do echo -n .; sleep 1; done

    VM_IPADDR=$(sudo virsh domifaddr $VM_NAME | grep vnet | sed -e 's|^\s*vnet[0-9]*.*ipv4\s*\([0-9.]*\)/[0-9]*|\1|g')
    echo "Got $VM_IPADDR"
    progress "Guest IP address is $VM_IPADDR"

    progress "Waiting for ssh to become available"
    while ! ssh -o "StrictHostKeyChecking no" kata@$VM_IPADDR "mkdir -p ~/go/src/github.com/kata-containers"; do
        sleep 1
    done

    progress "Initial rsync of kata-containers directory"
    rsync -av $directory/kata-containers kata@$VM_IPADDR:$vmdir/

    progress "Initial rsync of tests directory"
    rsync -av $directory/tests kata@$VM_IPADDR:$vmdir/

    progress "Launching CI setup in $VM_NAME (this will take a while)"
    ssh kata@$VM_IPADDR "cd $vmdir/tests; export GOPATH=~/go; .ci/setup.sh"

    cat > "$kci"/$distro-config <<EOF
VM_NAME="$VM_NAME"
VM_IPADDR=$VM_IPADDR
VM_DISK=$disk
EOF

    progress "Taking snapshot of $VM_NAME"
    sudo virsh snapshot-create-as $VM_NAME --name initial-snapshot --description "Initial snapshot of $VM_NAME after Kata CI setup"

}

if $install ; then
    vm_install
else
    source "$kci"/$distro-config

    if $revert ; then
        progress "Reverting to initial snapshot of $VM_NAME"
        sudo virsh snapshot-revert $VM_NAME initial-snapshot
    fi

    progress "Updating rsync of kata-containers directory"
    rsync -av $directory/kata-containers kata@$VM_IPADDR:$vmdir/

    progress "Updating rsync of tests directory"
    rsync -av $directory/kata-containers kata@$VM_IPADDR:$vmdir/
fi

if [ ! -z "$job" ]; then
    job="CI_JOB=\"$job\""
fi

progress "Cleanup previous runs"
ssh kata@$VM_IPADDR "rm -rf /etc/cni/net.d .kube"

progress "Launching tests"
ssh kata@$VM_IPADDR "cd $vmdir/tests; export GOPATH=~/go; $job .ci/run.sh" | tee "$kci/$distro.log"
